export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";

export const INIT_NEW_USER_LOCATIONS = "INIT_NEW_USER_LOCATIONS";
export const FETCH_USER_LOCATIONS = "FETCH_USER_LOCATIONS";
export const ADD_USER_LOCATION = "ADD_USER_LOCATION";
export const DELETE_USER_LOCATION = "DELETE_USER_LOCATION";
