// Auth Action Types
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";

// Location Action Types
export const FETCH_USER_LOCATIONS = "FETCH_USER_LOCATIONS";
export const FETCH_USER_LOCATIONS_SUCCESS = "FETCH_USER_LOCATIONS_SUCCESS";
export const RESET_LOCATIONS = "RESET_LOCATIONS";
export const ADD_USER_LOCATION = "ADD_USER_LOCATION";
export const DELETE_USER_LOCATION = "DELETE_USER_LOCATION";

// Weather Action Types
export const SELECT_LOCATION = "SELECT_LOCATION";
